name: Run eviction scraper notebook

on:
  workflow_dispatch: {}   # allows manual run
  schedule:
    # 4:17 AM Eastern (EDT right now = 08:17 UTC)
    - cron: "19 21 * * *"

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute notebook with papermill
        run: |
          papermill "VA Court Eviction Scraper - Final 3 16 25.ipynb" "output.ipynb"

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: output.ipynb
